### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by JakeFlanagan** [dhernandez98/pokespawn#3]
I've created a telegram not added it to a channel as an admin, add the telegram token, gmapi key and gave it the channel name with the bot inside. But when I run everything all all I get is network error trying again in 2 seconds. I have all the twitter areas still commented.

If you have any ideas can you let me know, I finish work in a couple of hours so if you want the code files I'll send them. Thanks in advance!

When I get in

**Comment by JakeFlanagan** [comment]
Added not as an admin *

**Comment by JakeFlanagan** [comment]
Bot *

**Comment by dhernandez98** [comment]
Hello! Thanks for using PokeSpawn.

In channels, only administrators are able to send messages. You **must** add your bot in the channel as an administrator in order to send alerts.

If this doesn't fix your problem, can you send me your pokespawn.py file? Delete all the personal information, keys...

Regards ^-^/
